#!/usr/bin/env python

import rospy

from sensor_msgs.msg import BatteryState
from std_msgs.msg import Header

NaN = float('nan')

def status_cb(data, node):
    node.status_callback(data)

class PowerStatusRelayNode:
    def __init__(self):
        rospy.init_node('dingo_power_monitor')

    def start(self):
        self.mcu_sub = rospy.Subscriber('/battery/status', BatteryState, status_cb, self)
        self.battery_pub = rospy.Publisher('/export/rocksteady/bms/battery_status', BatteryState, queue_size=1)

    def status_callback(self, data):
        # Dingo already publishes the right message format, so just relay it as-is
        # TODO: replace this node with a topic_tools relay?
        # Keeping this around for now for consistency with melodic-devel
        self.battery_pub.publish(data)

if __name__=='__main__':
    node = PowerStatusRelayNode()
    node.start()
    rospy.spin()
